baseURL = 'https://storage.googleapis.com/cloud-storage-site-vrr11/'
languageCode = 'en-us'
title = 'Vivek Rajkumar CS1660 Final Project'
theme = 'ananke'

[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
name = "production"

# URL specifies the Go Cloud Development Kit URL to deploy to. Examples:
URL = "gs://cloud-storage-site-vrr11"

# Google Cloud Storage -- see https://gocloud.dev/howto/blob/#gcs
#URL = "gs://<Bucket Name>"